# Generated by Django 6.0.4 on 2026-05-13 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ims_backend', '0002_paciente_comuna_paciente_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='public_key',
        ),
        migrations.AddField(
            model_name='despacho',
            name='creado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario de control que creó el despacho', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleinsumoatencion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='eva',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='fio2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='fr',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='gcs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='hgt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signosvitales',
            name='hora',
            field=models.CharField(default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='asignado_por',
            field=models.ForeignKey(blank=True, help_text='Usuario de control que asignó el despacho', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despachos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleinsumoatencion',
            name='dosis',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
        migrations.CreateModel(
            name='Cronologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_llamada', models.CharField(blank=True, max_length=4, null=True)),
                ('despacho_movil', models.CharField(blank=True, max_length=4, null=True)),
                ('llegada_qth1', models.CharField(blank=True, max_length=4, null=True)),
                ('salida_qth1', models.CharField(blank=True, max_length=4, null=True)),
                ('llegada_qth2', models.CharField(blank=True, max_length=4, null=True)),
                ('salida_qth2', models.CharField(blank=True, max_length=4, null=True)),
                ('categoria', models.CharField(max_length=2)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crono_atencion', to='ims_backend.atencion')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreInforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_informe', models.CharField(blank=True, max_length=250, null=True)),
                ('motivo_llamado', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_paciente', models.CharField(blank=True, max_length=150, null=True)),
                ('atencion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preinforme_atencion', to='ims_backend.atencion')),
            ],
        ),
    ]
