name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_django:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy test_deploy_repo_reformed
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_2}}
          username: ${{secrets.USER_SERVER_2}}
          key: ${{secrets.SSH_KEY}}
          script: |
                  cd ~/product/imSystem_Backend
                  git fetch origin main
                  git reset --hard origin/main
                  cd ~/product/imSystem_Backend/backend/imSystem/scripts
                  bash daily.sh
  deploy_celery:
    runs-on: ubuntu-latest
    needs: deploy_django
    steps:
      - name: Deploy Celery EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.EC2_BROKER_1}}
          username: ${{secrets.EC2_USER_BROKER_1}}
          key: ${{secrets.SSH_KEY}}
          timeout: 60s
          command_timeout: 30m
          script: |
            cd ~/product/imSystem_Backend
            git fetch origin main
            git reset --hard origin/main
            cd ~/product/imSystem_Backend/backend/imSystem/scripts
            bash daily_celery.sh
