name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy SSH Server 2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SERVER_2}}
          username: ${{secrets.USER_SERVER_2}}
          key: ${{secrets.SSH_KEY}}
          script: |
           cd ~/product/imSystem_Backend
           git pull origin main
           cd ~/product/imSystem_Backend/backend/imSystem/scripts
           bash daily.sh
